## Повторение примеров из раздела 1.3.3

In [1]:
2+3

5

In [3]:
5+4; #подавление вывода

In [4]:
?println

search: println print sprint pointer printstyled



```julia
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` to `io` followed by a newline. If `io` is not supplied, prints to the default output stream [`stdout`](@ref).

See also [`printstyled`](@ref) to add colors etc.

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello", ',', " world.")

julia> String(take!(io))
"Hello, world.\n"
```


In [5]:
;pwd

/home/zrdagdelen/work/study/2026-2027/Компьютерный практикум по статистическому анализу данных/computer-practice/labs/lab01


In [6]:
;whoami

zrdagdelen


In [7]:
;date

ср 09 сент 2026 21:24:30 MSK


In [13]:
#типы данных
println("type of 5: ",typeof(5))
println("type of 5.0: ",typeof(5.0))
println("type of 'hello': ",typeof("hello"))
println("type of true: ",typeof(true))

type of 5: Int64
type of 5.0: Float64
type of 'hello': String
type of true: Bool


In [15]:
#Приведение типов
convert(Float64, 5)
Int64(5.0)
parse(Int64, "123")

123

In [17]:
#Определение функций 
#длинная запись
function f(x)
    x^2
end
f(4)

16

In [18]:
#короткая запись
g(x) = x^2
g(8)

64

In [19]:
#Массивы и матрицы

#векторы
a = [4 7 6]   # вектор-строка
b = [1, 2, 3] # вектор-столбец
a[2], b[2]


(7, 2)

In [21]:
#матрица
a = 1; b = 2; c = 3; d = 4
Am = [a b; c d]
Am[1,1], Am[1,2], Am[2,1], Am[2,2]

(1, 2, 3, 4)

In [23]:
#умножение матриц
aa = [1 2]
AA = [1 2; 3 4]
aa * AA * aa'

1×1 Matrix{Int64}:
 27

## Задания для самостоятельной работы

### Задание 1. Функции ввода/вывода

In [27]:
# print и println
print("Hello ")
println("World!")

# show
show("Hello")

# readline (ввод с клавиатуры)
println("Введите ваше имя:")
name = readline()
println("Привет, $name !")

# запись в файл
open("test.txt", "w") do f
    write(f, "Это тестовая запись")
end

# чтение из файла
open("test.txt", "r") do f
    content = read(f, String)
    println("Содержимое файла: $content")
end

# readlines (чтение всех строк)
open("test.txt", "r") do f
    lines = readlines(f)
    println("Строки: $lines")
end


Hello World!
"Hello"Введите ваше имя:


stdin>  Zeynep


Привет, Zeynep !
Содержимое файла: Это тестовая запись
Строки: ["Это тестовая запись"]


### Задание 2. Функция parse()

In [29]:
# преобразование строки в Int
x = parse(Int64, "456")
println(x, " тип: ", typeof(x))

# преобразование в Float
y = parse(Float64, "3.1415")
println(y, " тип: ", typeof(y))

# попытка преобразовать нечисловую строку (вызовет ошибку)
parse(Int64, "abc")

456 тип: Int64
3.1415 тип: Float64


LoadError: ArgumentError: invalid base 10 digit 'a' in "abc"

### Задание 3. Математические операции

In [30]:
a = 10
b = 3

println("a = $a, b = $b")
println("Сложение: ", a + b)
println("Вычитание: ", a - b)
println("Умножение: ", a * b)
println("Деление: ", a / b)
println("Целочисленное деление: ", div(a, b))
println("Остаток от деления: ", rem(a, b))
println("Возведение в степень: ", a^b)
println("Квадратный корень из a: ", sqrt(a))
println("a > b: ", a > b)
println("a == b: ", a == b)
println("Логическое И: ", (a > 5) && (b < 5))
println("Логическое ИЛИ: ", (a > 5) || (b > 5))

a = 10, b = 3
Сложение: 13
Вычитание: 7
Умножение: 30
Деление: 3.3333333333333335
Целочисленное деление: 3
Остаток от деления: 1
Возведение в степень: 1000
Квадратный корень из a: 3.1622776601683795
a > b: true
a == b: false
Логическое И: true
Логическое ИЛИ: true


### Задание 4. Операции с матрицами и векторами

In [34]:
using LinearAlgebra
A = [1 2; 3 4]
B = [5 6; 7 8]
v = [1, 2]

println("Матрица A:")
display(A)
println("Матрица B:")
display(B)
println("Вектор v:")
display(v)

println("Сложение матриц A + B:")
display(A + B)

println("Вычитание матриц A - B:")
display(A - B)

println("Умножение матрицы на скаляр (2 * A):")
display(2 * A)

println("Транспонирование A':")
display(A')

println("Скалярное произведение v · v: ", dot(v,v))

println("Умножение матрицы на вектор A * v:")
display(A * v)

Матрица A:


2×2 Matrix{Int64}:
 1  2
 3  4

Матрица B:


2×2 Matrix{Int64}:
 5  6
 7  8

Вектор v:


2-element Vector{Int64}:
 1
 2

Сложение матриц A + B:


2×2 Matrix{Int64}:
  6   8
 10  12

Вычитание матриц A - B:


2×2 Matrix{Int64}:
 -4  -4
 -4  -4

Умножение матрицы на скаляр (2 * A):


2×2 Matrix{Int64}:
 2  4
 6  8

Транспонирование A':


2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

Скалярное произведение v · v: 5
Умножение матрицы на вектор A * v:


2-element Vector{Int64}:
  5
 11